### PR TITLE
Fix build on FreeBSD and add make it all build with bazel

### PR DESCRIPTION
**Pull request by dforsyth**
I couldn't get tests working easily so I stopped trying but otherwise everything works for me.

The bazel bits need https://github.com/dforsyth/bzl for the gperf rule

### CODE REVIEW

**Review by eklitzke — CHANGES_REQUESTED** [review]
This bazel code is completely wrong, NAK!

**Comment by dforsyth** [comment]
wrong as usual!

**Comment by rcr** [comment]
I'll take the BSD fixes if you update the PR, but hard no on the bazel. Why did you do this David???

**Comment by dforsyth** [comment]
the build is broken on freebsd even with my changes gl

**Pull request closed without merging**
